### ISSUE TITLE
Issue building SBOM

### ISSUE THREAD

**Issue by vpetersson** [anthonyharrison/sbom4rust#1]
Hi @anthonyharrison,

I tried this on the [Screenly CLI](https://github.com/Screenly/cli/) repo. However, I was unable to get it working. I must admit that I didn't dig too deep, but maybe I'm missing something obvious.

```bash
$ pip install git+https://github.com/anthonyharrison/sbom4rust.git
[...]
$ sbom4rust -a screenly-cli --sbom spdx --format json                                                                                                                                                                     Traceback (most recent call last):
  File "/Users/mvip/code/screenly/cli/venv/bin/sbom4rust", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/mvip/code/screenly/cli/venv/lib/python3.11/site-packages/sbom4rust/cli.py", line 121, in main
    sbom_scan.process_dependency()
  File "/Users/mvip/code/screenly/cli/venv/lib/python3.11/site-packages/sbom4rust/scanner.py", line 66, in process_dependency
    self.add_entry(self.DEFAULT_PARENT, entry["name"], entry["version"])
  File "/Users/mvip/code/screenly/cli/venv/lib/python3.11/site-packages/sbom4rust/scanner.py", line 163, in add_entry
    if len(originator.split()) > 3:
           ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by anthonyharrison** [comment]
@vpetersson Found the problem. It was because there was missing metadata in package.

**Comment by vpetersson** [comment]
Awesome! That worked.
